### ISSUE TITLE
first 🙋‍♂️

### ISSUE THREAD

**Issue by ipatch** [dehesselle/mibap#1]
Compiling Inkscape from 0.92.x will require GTK2 from what I have gathered.  That said, build against a git clone of the Inkscape source from gitlab either from the 1.x alpha branch and if you're feeling adventurous checkout master, as I didn't have any issues build from master the other day.

cheers.

**Comment by dehesselle** [comment]
Hi 😃! 0.92.x being GTK2 is in line with my prior experiences. I'll dig in deeper in the next few days. Thanks again!

**Comment by ipatch** [comment]
Not sure if you picked up on it or not, but 0.92.x requires GTK2 whereas the 1.x requires GTK3.

**Comment by dehesselle** [comment]
Yes, I did. Sorry if I was unclear.
